const {REACT_APP_BASE_URL_REST, REACT_APP_IS_MOCKUP, REACT_APP_BASE_URL_MOBILE} = process.env;

export const BASE_URL_REST = REACT_APP_BASE_URL_REST;
export const BASE_URL_MOBILE = REACT_APP_BASE_URL_MOBILE;
export const IS_MOCKUP = REACT_APP_IS_MOCKUP === 'true';
