import MockImg from 'assets/images/mockImg.png';
import MockQR from 'assets/images/mockQR.png';
import {ReactComponent as IconMap} from 'assets/images/mockMap.svg';
import {IListSolution} from 'pages/interactive/model/listSolution';

export const bodyPlan: {[key: string]: IListSolution} = {
  z1: {
    id: 1,
    text: 'Care Living Solutin',
    subTitle: 'ชั้น 1',
    image: MockImg,
    qrCode: MockQR,
    listDetail: ['ปรึกษาผู้เชี่ยวชาญสร้างบ้าน', 'ปรับปรุงบ้าน'],
    svgPlan: IconMap,
    detail: `     นวัตกรรมเพื่อบ้านสำหรับผู้ที่ให้ความสำคัญ เรื่องสุขภาพ พร้อมออกแบบที่อยู่อาศัยกลุ่ม Smart Elderly ตอบโจทย์เรื่องการอยู่อาศัยที่ดีขึ้นและปลอดภัย`,
  },
  z2: {
    id: 2,
    text: 'Home Inspiration Lounge',
    subTitle: 'ชั้น 1',
    image: MockImg,
    qrCode: MockQR,
    listDetail: ['ปรึกษาผู้เชี่ยวชาญสร้างบ้าน', 'ปรับปรุงบ้าน'],
    svgPlan: IconMap,
    detail: `     นวัตกรรมเพื่อบ้านสำหรับผู้ที่ให้ความสำคัญ เรื่องสุขภาพ พร้อมออกแบบที่อยู่อาศัยกลุ่ม Smart Elderly ตอบโจทย์เรื่องการอยู่อาศัยที่ดีขึ้นและปลอดภัย`,
  },
  z3: {
    id: 3,
    text: 'Living Design Studio',
    subTitle: 'ชั้น 1',
    image: MockImg,
    qrCode: MockQR,
    listDetail: ['ปรึกษาผู้เชี่ยวชาญสร้างบ้าน', 'ปรับปรุงบ้าน'],
    svgPlan: IconMap,
    detail: `     นวัตกรรมเพื่อบ้านสำหรับผู้ที่ให้ความสำคัญ เรื่องสุขภาพ พร้อมออกแบบที่อยู่อาศัยกลุ่ม Smart Elderly ตอบโจทย์เรื่องการอยู่อาศัยที่ดีขึ้นและปลอดภัย`,
  },
  z4: {
    id: 4,
    text: 'SCG Home Selected',
    subTitle: 'ชั้น 1',
    image: MockImg,
    qrCode: MockQR,
    listDetail: ['ปรึกษาผู้เชี่ยวชาญสร้างบ้าน', 'ปรับปรุงบ้าน'],
    svgPlan: IconMap,
    detail: `     นวัตกรรมเพื่อบ้านสำหรับผู้ที่ให้ความสำคัญ เรื่องสุขภาพ พร้อมออกแบบที่อยู่อาศัยกลุ่ม Smart Elderly ตอบโจทย์เรื่องการอยู่อาศัยที่ดีขึ้นและปลอดภัย`,
  },
  z5: {
    id: 5,
    text: 'Home & Decor Boutique',
    subTitle: 'ชั้น 1',
    image: MockImg,
    qrCode: MockQR,
    listDetail: ['ปรึกษาผู้เชี่ยวชาญสร้างบ้าน', 'ปรับปรุงบ้าน'],
    svgPlan: IconMap,
    detail: `     นวัตกรรมเพื่อบ้านสำหรับผู้ที่ให้ความสำคัญ เรื่องสุขภาพ พร้อมออกแบบที่อยู่อาศัยกลุ่ม Smart Elderly ตอบโจทย์เรื่องการอยู่อาศัยที่ดีขึ้นและปลอดภัย`,
  },
  z6: {
    id: 6,
    text: 'Outdoor & Garden Solution',
    subTitle: 'ชั้น 1',
    image: MockImg,
    qrCode: MockQR,
    listDetail: ['ปรึกษาผู้เชี่ยวชาญสร้างบ้าน', 'ปรับปรุงบ้าน'],
    svgPlan: IconMap,
    detail: `     นวัตกรรมเพื่อบ้านสำหรับผู้ที่ให้ความสำคัญ เรื่องสุขภาพ พร้อมออกแบบที่อยู่อาศัยกลุ่ม Smart Elderly ตอบโจทย์เรื่องการอยู่อาศัยที่ดีขึ้นและปลอดภัย`,
  },
  z7: {
    id: 7,
    text: 'Home & Living Solution',
    subTitle: 'ชั้น 1',
    image: MockImg,
    qrCode: MockQR,
    listDetail: ['ปรึกษาผู้เชี่ยวชาญสร้างบ้าน', 'ปรับปรุงบ้าน'],
    svgPlan: IconMap,
    detail: `     นวัตกรรมเพื่อบ้านสำหรับผู้ที่ให้ความสำคัญ เรื่องสุขภาพ พร้อมออกแบบที่อยู่อาศัยกลุ่ม Smart Elderly ตอบโจทย์เรื่องการอยู่อาศัยที่ดีขึ้นและปลอดภัย`,
  },
  z9: {
    id: 9,
    text: 'Cotto Life',
    subTitle: 'ชั้น 2',
    image: MockImg,
    qrCode: MockQR,
    listDetail: ['ปรึกษาผู้เชี่ยวชาญสร้างบ้าน', 'ปรับปรุงบ้าน'],
    svgPlan: IconMap,
    detail: `     นวัตกรรมเพื่อบ้านสำหรับผู้ที่ให้ความสำคัญ เรื่องสุขภาพ พร้อมออกแบบที่อยู่อาศัยกลุ่ม Smart Elderly ตอบโจทย์เรื่องการอยู่อาศัยที่ดีขึ้นและปลอดภัย`,
  },
  z10: {
    id: 10,
    text: 'Home Idea & Book Hub',
    subTitle: 'ชั้น 2',
    image: MockImg,
    qrCode: MockQR,
    listDetail: ['ปรึกษาผู้เชี่ยวชาญสร้างบ้าน', 'ปรับปรุงบ้าน'],
    svgPlan: IconMap,
    detail: `     นวัตกรรมเพื่อบ้านสำหรับผู้ที่ให้ความสำคัญ เรื่องสุขภาพ พร้อมออกแบบที่อยู่อาศัยกลุ่ม Smart Elderly ตอบโจทย์เรื่องการอยู่อาศัยที่ดีขึ้นและปลอดภัย`,
  },
  z11: {
    id: 11,
    text: 'Design Studio & Meeting Room',
    subTitle: 'ชั้น 2',
    image: MockImg,
    qrCode: MockQR,
    listDetail: ['ปรึกษาผู้เชี่ยวชาญสร้างบ้าน', 'ปรับปรุงบ้าน'],
    svgPlan: IconMap,
    detail: `     นวัตกรรมเพื่อบ้านสำหรับผู้ที่ให้ความสำคัญ เรื่องสุขภาพ พร้อมออกแบบที่อยู่อาศัยกลุ่ม Smart Elderly ตอบโจทย์เรื่องการอยู่อาศัยที่ดีขึ้นและปลอดภัย`,
  },
  z12: {
    id: 12,
    text: 'ExSpace',
    subTitle: 'ชั้น 3',
    image: MockImg,
    qrCode: MockQR,
    listDetail: ['ปรึกษาผู้เชี่ยวชาญสร้างบ้าน', 'ปรับปรุงบ้าน'],
    svgPlan: IconMap,
    detail: `     นวัตกรรมเพื่อบ้านสำหรับผู้ที่ให้ความสำคัญ เรื่องสุขภาพ พร้อมออกแบบที่อยู่อาศัยกลุ่ม Smart Elderly ตอบโจทย์เรื่องการอยู่อาศัยที่ดีขึ้นและปลอดภัย`,
  },
  z13: {
    id: 13,
    text: 'Home Smile',
    subTitle: 'ชั้น 3',
    image: MockImg,
    qrCode: MockQR,
    listDetail: ['ปรึกษาผู้เชี่ยวชาญสร้างบ้าน', 'ปรับปรุงบ้าน'],
    svgPlan: IconMap,
    detail: `     นวัตกรรมเพื่อบ้านสำหรับผู้ที่ให้ความสำคัญ เรื่องสุขภาพ พร้อมออกแบบที่อยู่อาศัยกลุ่ม Smart Elderly ตอบโจทย์เรื่องการอยู่อาศัยที่ดีขึ้นและปลอดภัย`,
  },
  z14: {
    id: 14,
    text: 'doo Deco',
    subTitle: 'ชั้น 3',
    image: MockImg,
    qrCode: MockQR,
    listDetail: ['ปรึกษาผู้เชี่ยวชาญสร้างบ้าน', 'ปรับปรุงบ้าน'],
    svgPlan: IconMap,
    detail: `     นวัตกรรมเพื่อบ้านสำหรับผู้ที่ให้ความสำคัญ เรื่องสุขภาพ พร้อมออกแบบที่อยู่อาศัยกลุ่ม Smart Elderly ตอบโจทย์เรื่องการอยู่อาศัยที่ดีขึ้นและปลอดภัย`,
  },
};
